
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vasud
 */
public class supplyframe extends javax.swing.JInternalFrame implements myvars{

    /**
     * Creates new form categoryframe
     */
    public supplyframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Suppliers");

        jLabel2.setText("Supplier name");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier Id", "Supplier Name", "Email ID", "Phone No."
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Delete");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Email ID");

        jLabel4.setText("Phone no.");

        jLabel5.setText("Supplier Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(468, 468, 468))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //Add Category
        try
        {
            Connection mycon=DriverManager.getConnection(myurl,dbuser,dbpass);
            try
            {
             String q="insert into suppliertable values(?,?,?,?)";
             PreparedStatement myst=mycon.prepareStatement(q);
             myst.setString(1, jLabel6.getText());
             myst.setString(2, jTextField1.getText());
            myst.setString(3, jTextField2.getText());
            myst.setString(4, jTextField3.getText());
             
            int count =myst.executeUpdate();
             
             if(count==1)
             {
                 JOptionPane.showMessageDialog(rootPane,"Supplier added Successfully");
                 getdata();
                 getsupid();
             }
             else
             {
                 JOptionPane.showMessageDialog(rootPane,"Supplier not added successfully");
             }
             // To imediately show the added category in table
//                        try
//                         {
//                          String s="select catid from categorytable where catname=?";
//                          PreparedStatement mystat=mycon.prepareStatement(s);
//                          mystat.setString(1, jTextField1.getText());
//
//                          ResultSet myres=mystat.executeQuery();
//
//                          if(myres.next()==true)
//                          {
//                           String catid= myres.getString("CatId");
//                           DefaultTableModel mymodel =(DefaultTableModel)jTable1.getModel();
//                           String catname=jTextField1.getText();
//                           Object row[]={catid,catname};
//                           mymodel.addRow(row);
//
//                         }
//
//                        }
//                       catch(Exception e)
//                         {
//                          JOptionPane.showMessageDialog(rootPane, "Error " + e.getMessage());
//                           }
        //contine add code
                          
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error "+e.getMessage());
            }
            finally
            {
                mycon.close();
            }
                    
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,"Error is "+e.getMessage());
                }
        clearfields();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // show previous categories as soon as frame opens
       getdata();
       getsupid();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // to show the selected category in fields
        String supidref= jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        
        try
        {
            Connection mycon=DriverManager.getConnection(myurl,dbuser,dbpass);
            try
            {
             String q="select * from suppliertable where supid=?";
             PreparedStatement myst=mycon.prepareStatement(q);
             myst.setString(1,supidref);
            
             ResultSet myres=myst.executeQuery();
             
             if(myres.next()==true)
             {
                 jLabel6.setText(myres.getString("SupId"));
               jTextField1.setText(myres.getString("SupName"));
               jTextField2.setText(myres.getString("EmailId"));
               jTextField3.setText(myres.getString("PhoneNo"));
               
                jButton2.setEnabled(true);
                jButton3.setEnabled(true);
 
            }
           else
              {
                JOptionPane.showMessageDialog(rootPane, "Cannot Fetch Data");
                 clearfields();
                 jButton2.setEnabled(false);
                 jButton3.setEnabled(false);
                }

           }
          catch(Exception e)
            {
             JOptionPane.showMessageDialog(rootPane, "Error " + e.getMessage());
              }
           finally
             {
              mycon.close();
              }
         }
        catch(Exception e)
          {
            JOptionPane.showMessageDialog(rootPane, "Error in connection " + e.getMessage());
           }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // Delete button
        int choice=JOptionPane.showConfirmDialog(rootPane, "Are you sure to delete this record","Confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE );
        
        if(choice==JOptionPane.YES_OPTION)
        {
        
        try
        {
            Connection mycon=DriverManager.getConnection(myurl,dbuser,dbpass);
            try
            {
             String supidref= jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
             String q="delete from suppliertable where supid=?";
             PreparedStatement myst=mycon.prepareStatement(q);
             myst.setString(1,supidref);
            
             int s=myst.executeUpdate();
             if(s==1)
             {
                JOptionPane.showMessageDialog(rootPane, "Supplier deleted Successfully");
                 clearfields();
                 getdata();
                 getsupid();
                 
                // Readding categories so that the deleted category is not shown
                
//                        try
//                        {
//                         DefaultTableModel mymodel1 =(DefaultTableModel)jTable1.getModel();
//                         String qu="select * from categorytable";
//                         PreparedStatement mysta= mycon.prepareStatement(qu);
//                         ResultSet myres=mysta.executeQuery();
//
//                         if(myres.next()==true)
//                         {
//                           do
//                           {
//
//                             String catid,catname;
//                             catid=myres.getString("CatId");
//                             catname=myres.getString("CatName");
//
//                            Object myrow[] = {catid,catname};
//
//                            mymodel1.addRow(myrow);
//                           }
//                            while(myres.next());
//
//                        }
//                        else
//                          {
//                            JOptionPane.showMessageDialog(rootPane, "No Records found");
//                             clearfields();
//
//                             mymodel.setRowCount(0);
//                            }
//
//                       }
//                      catch(Exception e)
//                        {
//                         JOptionPane.showMessageDialog(rootPane, "Error " + e.getMessage());
//                          }
                       
                 
                 jButton2.setEnabled(false);
                 jButton3.setEnabled(false);
            }
           else
              {
                JOptionPane.showMessageDialog(rootPane, "Supplier not deleted Successfully");
                 clearfields();
                 jButton2.setEnabled(false);
                 jButton3.setEnabled(false);
                 getsupid();
                }

           }
          catch(Exception e)
            {
             JOptionPane.showMessageDialog(rootPane, "Error " + e.getMessage());
              }
           finally
             {
              mycon.close();
              }
         }
        catch(Exception e)
          {
            JOptionPane.showMessageDialog(rootPane, "Error in connection " + e.getMessage());
           }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //update button
        try
        {
           Connection mycon=DriverManager.getConnection(myurl,dbuser,dbpass);
            try
            {
             String supidref= jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
             String q="update suppliertable set supname=?,emailid=?,phoneno=? where supid=?";
             PreparedStatement myst=mycon.prepareStatement(q);
             myst.setString(1, jTextField1.getText());
             myst.setString(2, jTextField2.getText());
             myst.setString(3, jTextField3.getText());
             myst.setString(4, supidref);
             
             int count =myst.executeUpdate();
             if(count==1)
             {
                 JOptionPane.showMessageDialog(rootPane,"Supplier updated Successfully");
                 clearfields();
                 getdata();
                 getsupid();
                // Readding categories so that the updated category is shown
                
//                        try
//                        {
//                         DefaultTableModel mymodel1 =(DefaultTableModel)jTable1.getModel();
//                         String qu="select * from categorytable";
//                         PreparedStatement mysta= mycon.prepareStatement(qu);
//                         ResultSet myres=mysta.executeQuery();
//
//                         if(myres.next()==true)
//                         {
//                           do
//                           {
//
//                             String catid,catname;
//                             catid=myres.getString("CatId");
//                             catname=myres.getString("CatName");
//
//                            Object myrow[] = {catid,catname};
//
//                            mymodel1.addRow(myrow);
//                           }
//                            while(myres.next());
//
//                        }
//                        else
//                          {
//                            JOptionPane.showMessageDialog(rootPane, "No Records found");
//                             clearfields();
//
//                             mymodel.setRowCount(0);
//                            }
//
//                       }
//                      catch(Exception e)
//                        {
//                         JOptionPane.showMessageDialog(rootPane, "Error " + e.getMessage());
//                          }
                       
                 
                 jButton2.setEnabled(false);
                 jButton3.setEnabled(false);
             }
             else
             {
                 JOptionPane.showMessageDialog(rootPane,"Supplier not updated successfully");
             }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error "+e.getMessage());
            }
            finally
            {
                mycon.close();
            }
                    
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,"Error is "+e.getMessage());
                }
        
    }//GEN-LAST:event_jButton3ActionPerformed
      
    void clearfields()
        {
            jTextField1.setText(null);
            jTextField2.setText(null);
            jTextField3.setText(null);
        }
    void getsupid()
    {
        try
        {
            Connection mycon=DriverManager.getConnection(myurl,dbuser,dbpass);
            try
            {
                String q="select * from suppliertable order by supid desc";
                PreparedStatement myst=mycon.prepareStatement(q);
                ResultSet myres = myst.executeQuery();

                if(myres.next())
                  { 
                    int supid = myres.getInt("supid");
                    supid++;
                    jLabel6.setText(String.valueOf(supid));
                   }
                 else
                  {
                    jLabel6.setText("1");
                    }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error "+e.getMessage());
            }
            finally
            {
                mycon.close();
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error is "+e.getMessage());
        }
    }
       void getdata()
       {
            try
        {
            Connection mycon=DriverManager.getConnection(myurl,dbuser,dbpass);
            try
            {
             DefaultTableModel mymodel =(DefaultTableModel)jTable1.getModel();
             String q="select * from suppliertable";
             PreparedStatement myst=mycon.prepareStatement(q);
             ResultSet myres=myst.executeQuery();
             
             if(myres.next()==true)
             {
                 mymodel.setRowCount(0);
               do
               {
                 
                 String supid,supname,emailid,phoneno;
                 supid=myres.getString("SupId");
                 supname=myres.getString("SupName");
                 emailid=myres.getString("EmailId");
                 phoneno=myres.getString("PhoneNo");
                 
                Object myrow[] = {supid,supname,emailid,phoneno};

                mymodel.addRow(myrow);
               }
                while(myres.next());
            
            }
           else
              {
                JOptionPane.showMessageDialog(rootPane, "No Records found");
                 clearfields();
                 
                 mymodel.setRowCount(0);
                }

           }
          catch(Exception e)
            {
             JOptionPane.showMessageDialog(rootPane, "Error " + e.getMessage());
              }
           finally
             {
              mycon.close();
              }
         }
        catch(Exception e)
          {
            JOptionPane.showMessageDialog(rootPane, "Error in connection " + e.getMessage());
           }
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
